In [1]:
import pandas as pd

In [72]:
df = pd.read_csv('submission_simpleLGBM.csv')
guide = pd.read_csv('guide_submit.csv')

In [52]:
copy = df.copy()

In [73]:
each_row_maxcol = df.iloc[:,1:].idxmax(axis=1)

for i,x in enumerate(each_row_maxcol):
    max_val = df.iloc[i,1:].max()
    df.iloc[i] = 0
    df.loc[i,x] = max_val

In [81]:
df['id'] = guide['id']

In [89]:
df.to_csv('submission_simpleLGBM_2.csv',index=False)

In [98]:
guide

,id,STAR_WHITE_DWARF,STAR_CATY_VAR,STAR_BROWN_DWARF,SERENDIPITY_RED,REDDEN_STD,STAR_BHB,GALAXY,SERENDIPITY_DISTANT,QSO,SKY,STAR_RED_DWARF,ROSAT_D,STAR_PN,SERENDIPITY_FIRST,STAR_CARBON,SPECTROPHOTO_STD,STAR_SUB_DWARF,SERENDIPITY_MANUAL,SERENDIPITY_BLUE
0,199991,0.00,0.00,0.0,0.03,0.0,0.00,0.00,0.00,0.00,0.0,0.97,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.00
1,199992,0.00,0.00,0.0,0.00,0.0,0.00,0.00,0.00,0.55,0.0,0.00,0.26,0.0,0.19,0.0,0.0,0.0,0.0,0.00
2,199993,0.00,0.00,0.0,0.00,0.0,0.00,0.99,0.00,0.00,0.0,0.00,0.01,0.0,0.00,0.0,0.0,0.0,0.0,0.00
3,199994,0.00,0.00,0.0,0.00,0.0,0.00,0.00,0.01,0.13,0.0,0.00,0.01,0.0,0.03,0.0,0.0,0.0,0.0,0.82
4,199995,0.00,0.00,0.0,0.00,0.0,0.00,0.00,0.00,0.00,0.0,1.00,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10004,209995,0.07,0.04,0.0,0.00,0.0,0.01,0.00,0.01,0.14,0.0,0.00,0.09,0.0,0.02,0.0,0.0,0.0,0.0,0.62
10005,209996,0.04,0.03,0.0,0.00,0.0,0.00,0.00,0.00,0.30,0.0,0.00,0.06,0.0,0.06,0.0,0.0,0.0,0.0,0.51
10006,209997,0.00,0.00,0.0,0.00,0.0,0.00,0.00,0.00,0.99,0.0,0.00,0.00,0.0,0.01,0.0,0.0,0.0,0.0,0.00
10007,209998,0.00,0.00,0.0,0.00,0.0,0.00,0.00,0.00,1.00,0.0,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.00
10008,209999,0.00,0.00,0.0,0.00,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.0,1.0,0.0,0.0,0.00

In [90]:
df.iloc[:,1:].idxmax(axis=1)

0          STAR_SUB_DWARF
1           STAR_CATY_VAR
2        STAR_WHITE_DWARF
3              REDDEN_STD
4          STAR_SUB_DWARF
               ...
10004          REDDEN_STD
10005          REDDEN_STD
10006       STAR_CATY_VAR
10007       STAR_CATY_VAR
10008      STAR_RED_DWARF
Length: 10009, dtype: object

In [92]:
guide.iloc[:,1:].idxmax(axis=1)

0          STAR_RED_DWARF
1                     QSO
2                  GALAXY
3        SERENDIPITY_BLUE
4          STAR_RED_DWARF
               ...
10004    SERENDIPITY_BLUE
10005    SERENDIPITY_BLUE
10006                 QSO
10007                 QSO
10008    SPECTROPHOTO_STD
Length: 10009, dtype: object

In [97]:
guide.iloc[10007,1:]

STAR_WHITE_DWARF       0.0
STAR_CATY_VAR          0.0
STAR_BROWN_DWARF       0.0
SERENDIPITY_RED        0.0
REDDEN_STD             0.0
STAR_BHB               0.0
GALAXY                 0.0
SERENDIPITY_DISTANT    0.0
QSO                    1.0
SKY                    0.0
STAR_RED_DWARF         0.0
ROSAT_D                0.0
STAR_PN                0.0
SERENDIPITY_FIRST      0.0
STAR_CARBON            0.0
SPECTROPHOTO_STD       0.0
STAR_SUB_DWARF         0.0
SERENDIPITY_MANUAL     0.0
SERENDIPITY_BLUE       0.0
Name: 10007, dtype: float64