[예제] 파이썬의 데이타 주무르기


## 서울시 자치구 인구대비 CCTV 현황

1. 서울시 자치구 연도별 CCTV 현황

    서울열린데이타 : https://data.seoul.go.kr 에서 cctv 검색하여 csv 파일 다운로드
    

2. 서울시 주민등록인구 (구별) 통계

    서울열린데이타 : https://data.seoul.go.kr > 인구 > XLS 파일 다운로드

## 1. 서울시 자치구 연도별 CCTV 현황

In [2]:
# 1. 데이타 살펴보기

import pandas as pd
import numpy as np

""" 1. 서울시 자치구 연도별 CCTV 현황 """
cctvSeoul = pd.read_csv('./data/cctv_in_seoul.csv',encoding='utf-8')
cctvSeoul.head()
# (1) CCTV가 많은 순으로 정렬하여 상위 5위 



# (2) 2014~2016년 3년간 CCTV 증가율을 추가
#     3년동안의 증가율 = ( 2014년 + 2015년 + 2016년 ) / 2013년도 이전 * 100
#     3년간 증가율 높은 순으로 출력

   기관명    소계  2013년도 이전  2014년  2015년  2016년
0  강남구  3238       1292    430    584    932
1  강동구  1010        379     99    155    377
2  강북구   831        369    120    138    204
3  강서구   911        388    258    184     81
4  관악구  2109        846    260    390    613

In [3]:
cctvSeoul.sort_values(ascending=False,by='소계').iloc[:5]

    기관명    소계  2013년도 이전  2014년  2015년  2016년
0   강남구  3238       1292    430    584    932
18  양천구  2482       1843    142     30    467
14  서초구  2297       1406    157    336    398
4   관악구  2109        846    260    390    613
21  은평구  2108       1138    224    278    468

In [4]:
def func_1(x):
    result = (x[1]+x[2]+x[3]) / x[0] * 100
    return result

cctvSeoul['3년간 증가율'] = cctvSeoul[["2013년도 이전","2014년","2015년","2016년"]].apply(func_1,axis=1)
cctvSeoul.rename(columns={cctvSeoul.columns[0] :"구별"}, inplace = True)
cctvSeoul.sort_values(by='3년간 증가율',ascending=False)

      구별    소계  2013년도 이전  2014년  2015년  2016년     3년간 증가율
22   종로구  1619        464    314    211    630  248.922414
9    도봉구   825        238    159     42    386  246.638655
12   마포구   980        314    118    169    379  212.101911
8    노원구  1566        542     57    451    516  188.929889
1    강동구  1010        379     99    155    377  166.490765
19  영등포구  1277        495    214    195    373  157.979798
0    강남구  3238       1292    430    584    932  150.619195
4    관악구  2109        846    260    390    613  149.290780
23    중구  1023        413    190     72    348  147.699758
11   동작구  1302        544    341    103    314  139.338235
3    강서구   911        388    258    184     81  134.793814
2    강북구   831        369    120    138    204  125.203252
17   송파구  1081        529     21     68    463  104.347826
7    금천구  1348        674     51    269    354  100.000000
21   은평구  2108       1138    224    278    468   85.237258
15   성동구  1327        730     91    241    265   81.780822
24   중랑구   916        509    121    177    109   79.960707
10  동대문구  1870       1070     23    198    579   74.766355
6    구로구  1884       1142    173    246    323   64.973730
16   성북구  1651       1009     78    360    204   63.627354
14   서초구  2297       1406    157    336    398   63.371266
5    광진구   878        573     78     53    174   53.228621
20   용산구  2096       1368    218    112    398   53.216374
13  서대문구  1254        844     50     68    292   48.578199
18   양천구  2482       1843    142     30    467   34.671731

## 2. 서울시 주민등록인구 (구별) 통계

[ 파일읽기 ]  

popsSeoul = pd.read_excel('./dataset/pops_in_seoul.xls')

수정하고 데이타 정리

---
[ 출력결과 ]  popsSeoul.head(5)

<img src='images/그림1.PNG' width='80%' height='100'>

In [5]:
names = ['구별','인구수','한국인','외국인','고령자']

# popsSeoul = pd.read_excel('./data/pops_in_seoul.xls')
popsSeoul_fil = pd.read_excel('./data/pops_in_seoul.xls', usecols=[1,3,6,9,13], names=names , skiprows=[0,1,2])

In [6]:
def func_foreign(x):
    result = x[1] / x[0] * 100
    return result

def func_old(x):
    result = x[1] / x[0] * 100
    return result

popsSeoul_fil['외국인비율'] = popsSeoul_fil[['인구수','외국인']].apply(func_foreign,axis=1)
popsSeoul_fil['고령자비율'] = popsSeoul_fil[['인구수','고령자']].apply(func_old,axis=1)

popSeoul = popsSeoul_fil

##  3. 두 데이타프레임을 합치고 분석

    (1) 두 데이타프레임의 행과 열의 수 확인
    
        > cctvSeoul.shape
        
        > popsSeoul.shape

    (2) 연결 ( mergy 함수  )
        먼저 합치고 필요한 컬럼을 추출하기보단
        각각 필요한 컬럼을 추리고 나서 합치는 것을 권장
        
        
---        
[ 출력결과 ]

<img src='images/그림2.PNG'>

In [7]:
pd.merge(cctvSeoul,popSeoul)

,구별,소계,2013년도 이전,2014년,2015년,2016년,3년간 증가율,인구수,한국인,외국인,고령자,외국인비율,고령자비율
0,강남구,3238,1292,430,584,932,150.619195,547453,542364,5089,67085,0.929578,12.254020
1,강동구,1010,379,99,155,377,166.490765,431920,427573,4347,58770,1.006436,13.606686
2,강북구,831,369,120,138,204,125.203252,322915,319164,3751,58196,1.161606,18.022080
3,강서구,911,388,258,184,81,134.793814,603611,596949,6662,79660,1.103691,13.197241
4,관악구,2109,846,260,390,613,149.290780,520040,501957,18083,72249,3.477233,13.892970
5,광진구,878,573,78,53,174,53.228621,371063,355559,15504,45619,4.178266,12.294139
6,구로구,1884,1142,173,246,323,64.973730,438486,404497,33989,61801,7.751445,14.094179
7,금천구,1348,674,51,269,354,100.000000,254021,233917,20104,35739,7.914306,14.069309
8,노원구,1566,542,57,451,516,188.929889,548160,543752,4408,77096,0.804145,14.064507
9,도봉구,825,238,159,42,386,246.638655,341649,339413,2236,55964,0.654473,16.380554
10,동대문구,1870,1070,23,198,579,74.766355,364338,348052,16286,57165,4.470025,15.690101
11,동작구,1302,544,341,103,314,139.338235,409385,396203,13182,59479,3.219952,14.528866
12,마포구,980,314,118,169,379,212.101911,386359,375077,11282,50833,2.920082,13.156934
13,서대문구,1254,844,50,68,292,48.578199,323080,310313,12767,50456,3.951653,15.617185
14,서초구,2297,1406,157,336,398,63.371266,438163,433951,4212,54751,0.961286,12.495578
15,성동구,1327,730,91,241,265,81.780822,316463,308221,8242,42767,2.604412,13.514060
16,성북구,1651,1009,78,360,204,63.627354,447687,435868,11819,67782,2.640014,15.140489
17,송파구,1081,529,21,68,463,104.347826,673507,666635,6872,81364,1.020331,12.080647
18,양천구,2482,1843,142,30,467,34.671731,468145,464185,3960,58045,0.845892,12.398936
19,영등포구,1277,495,214,195,373,157.979798,403600,367778,35822,55673,8.875619,13.794103
20,용산구,2096,1368,218,112,398,53.216374,245090,228999,16091,37640,6.565343,15.357624
21,은평구,2108,1138,224,278,468,85.237258,487666,483197,4469,77420,0.916406,15.875620
22,종로구,1619,464,314,211,630,248.922414,163026,153065,9961,26742,6.110068,16.403518
23,중구,1023,413,190,72,348,147.699758,135633,125725,9908,22005,7.305007,16.223928
24,중랑구,916,509,121,177,109,79.960707,408147,403209,4938,61830,1.209858,15.148954

## 4. 분석하기 

        외국인비율, 고령자비율, 인구수와 CCTV 수와 상관있나?

In [2]:
""" 4. 분석하기 
        외국인비율, 고령자비율, 인구수와 CCTV 수와 상관있나?
        
        상관계수로 확인 : numpy.corrcoef()
            0.1이하 상관없음
            0.3이하 약한 상관관계
            0.7이하 뚜렷한 상관관계
"""
import numpy as np

# print( np.corrcoef(result['소계'], result['외국인비율']) )
# print( np.corrcoef(result['소계'], result['고령자비율']) )
# print( np.corrcoef(result['소계'], result['인구수']) )

## 5. 시각화로 분석을 보여주기

## 추가적으로 분석을 하여 결과 도출