## 인터넷 상의 데이타 읽기

1. Url 상의 csv 읽기 :  pandas.read_csv(url) 

2. 크롤링하여 읽기

    ` requests / Selenium 라이브러리 활용
    ` pandas.read_html(url, .. ) : 내부적으로 requests 라이브러리 사용
    
3. pandas-datareader 라이브러리

    ` 내부적으로 requests 라이브러리 사용
    ` 버전에 따라 오류 발생
    ` Google Finance/Yahoo Finance 등에서 데이타 지원 -> 연결이 안될 수도 있음

    [참고] Kosdaq 종목코드 CSV URL : https://goo.gl/3p3dSG

        - https://gist.githubusercontent.com/allieus/5ce98166166d06ee9060e6a261e812dc/raw
        - 위 주소를 pandas.read_csv(여기)에 붙이기

    [참고] Kospi 종목코드 CSV URL : https://goo.gl/aUHznC

        - https://gist.githubusercontent.com/allieus/733725662c644ab56c9db9d3cdf77ed1/raw

In [3]:
import pandas as pd

""" (1) read_csv() """
df = pd.read_csv('https://gist.githubusercontent.com/allieus/5ce98166166d06ee9060e6a261e812dc/raw')
df.head()

        종목명    종목코드
0     제일홀딩스    3380
1  하나금융9호스팩  261200
2    교보7호스팩  267320
3      보라티알  250000
4    한화수성스팩  265920

In [2]:
""" (2) pandas.read_html()
        ` 웹페이지 크롤링을 쉽게 도와주는 만능 라이브러리 X (아님)
        ` 웹 페이지 상의 HTML table을 한번에 로딩하기 위한 목적임
          그러나 데이터 외에 다른 문자열이 있으면 곤란
"""
     
# 한국천문연구원 > 생활천문관 > 월별 음양력
# https://astro.kasi.re.kr/life/pageView/5

' (2) pandas.read_html()\n        ` 웹페이지 크롤링을 쉽게 도와주는 만능 라이브러리 X (아님)\n        ` 웹 페이지 상의 HTML table을 한번에 로딩하기 위한 목적임\n          그러나 데이터 외에 다른 문자열이 있으면 곤란\n'

In [ ]:
# pip install --upgrade pandas-datareader

In [3]:
""" (3) pandas-datareader 라이브러리 
        ` 설치 필요
        ` 최신버전 업그레이드 필수
        ` pip install --upgrade pandas-datareader
        ` Anaconda Prompt에서 확인 가능(반드시 관리자 권한으로 실행) : conda install pandas-datareader
        ` Jupyter 에서 !pip install --upgrade pandas-datareader
"""

' (3) pandas-datareader 라이브러리 \n        ` 설치 필요\n        ` 최신버전 업그레이드 필수\n        ` pip install --upgrade pandas-datareader\n        ` Anaconda Prompt에서 확인 가능(반드시 관리자 권한으로 실행) : conda install pandas-datareader\n        ` Jupyter 에서 !pip install --upgrade pandas-datareader\n'

In [10]:
import pandas_datareader as pdr

pdr.get_data_yahoo('035420.KS','2019-08-01','2019-08-31')

                High       Low      Open     Close    Volume  Adj Close
Date
2019-08-01  141500.0  138500.0  139500.0  140500.0  460049.0   140500.0
2019-08-05  142000.0  135500.0  141000.0  138000.0  733982.0   138000.0
2019-08-06  140000.0  132000.0  134000.0  138500.0  610095.0   138500.0
2019-08-07  139500.0  136000.0  139000.0  137500.0  336416.0   137500.0
2019-08-08  142000.0  136500.0  139500.0  140000.0  496443.0   140000.0
2019-08-09  145000.0  140500.0  142000.0  142500.0  368133.0   142500.0
2019-08-12  144500.0  140500.0  142500.0  140500.0  217292.0   140500.0
2019-08-13  144500.0  138500.0  139000.0  142500.0  352863.0   142500.0
2019-08-14  143000.0  138500.0  142500.0  139000.0  433070.0   139000.0
2019-08-16  140500.0  137500.0  138500.0  139500.0  351686.0   139500.0
2019-08-19  141000.0  138000.0  139000.0  139000.0  487500.0   139000.0
2019-08-20  145500.0  139000.0  139000.0  145500.0  556246.0   145500.0
2019-08-21  148500.0  142500.0  144500.0  147500.0  514109.0   147500.0
2019-08-22  150500.0  147500.0  148000.0  148000.0  499537.0   148000.0
2019-08-23  149000.0  145500.0  149000.0  148500.0  491690.0   148500.0
2019-08-26  147000.0  143000.0  145500.0  143500.0  423695.0   143500.0
2019-08-27  147500.0  141500.0  144000.0  146500.0  904199.0   146500.0
2019-08-28  147500.0  144500.0  146500.0  146500.0  309159.0   146500.0
2019-08-29  146500.0  143500.0  146500.0  145000.0  408164.0   145000.0
2019-08-30  149000.0  144500.0  146000.0  146500.0  424498.0   146500.0